[package]
name = "zune-qoi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zune-core = { path = "../zune-core", version = "0.2.1" }
log = "0.4.17"

[dev-dependencies]
nanorand = "0.7.0"
rapid-qoi = "0.6.1"

[dev-dependencies.criterion]
version = "0.4.0"
default-features = false
features = ["html_reports"]

[[bench]]
name = "decode"
harness = false
