[package]
name = "zune-bmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zune-core = { version = "0.2", path = "../zune-core" }
log = "0.4.17"