## Add tests to ensure no-std crates are no-std
name: Build no std

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        # Target below does not have a CI
      - run: rustup target add x86_64-unknown-uefi
      - run: cargo build -p zune-inflate --target x86_64-unknown-uefi --no-default-features
      - run: cargo build -p zune-jpeg    --target x86_64-unknown-uefi --no-default-features
      - run: cargo build -p zune-png     --target x86_64-unknown-uefi --no-default-features

