name: Wasm build action
  


on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jetli/wasm-pack-action@v0.4.0
      - name: Build wasm module
        run: wasm-pack build ./zune-wasm
  
